# Generated by Django 5.2.18 on 2026-10-09 11:41

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.fields
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models

from tutortrack.core.migrations_utils import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_search_indexes'),
        ('tenancy', '0007_encrypt_tax_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subject', 'order', 'name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('centre', 'Centre'), ('client_home', "Client's home"), ('tutor_home', "Tutor's home"), ('school', 'School'), ('online', 'Online'), ('other', 'Other')], default='centre', max_length=12)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('online_url', models.URLField(blank=True, default='')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.address')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='catalogue.location')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['location', 'name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('public_description', models.TextField(blank=True, default='')),
                ('format', models.CharField(choices=[('one_to_one', 'One to one'), ('small_group', 'Small group'), ('class', 'Class')], default='one_to_one', max_length=12)),
                ('max_students', models.PositiveIntegerField(default=1)),
                ('delivery_mode', models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='in_person', max_length=10)),
                ('default_duration_minutes', models.PositiveIntegerField(default=60)),
                ('allowed_durations', models.JSONField(blank=True, default=list)),
                ('pricing_unit', models.CharField(choices=[('per_hour', 'Per hour'), ('per_lesson', 'Per lesson'), ('per_student_per_lesson', 'Per student per lesson'), ('per_month', 'Per month'), ('per_term', 'Per term')], default='per_hour', max_length=25)),
                ('group_charge', models.CharField(choices=[('per_student', 'Each student pays the rate'), ('split', 'The rate is split between students')], default='per_student', max_length=12)),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('charge_rate', tutortrack.core.fields.RateField(currency_field='currency')),
                ('pay_unit', models.CharField(choices=[('per_hour', 'Per hour'), ('per_lesson', 'Per lesson')], default='per_hour', max_length=10)),
                ('pay_rate', tutortrack.core.fields.RateField(blank=True, currency_field='currency', null=True)),
                ('pay_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('revenue_account_code', models.CharField(blank=True, default='', max_length=30)),
                ('bookable_online', models.BooleanField(default=False)),
                ('colour', models.CharField(default='#2563eb', max_length=7)),
                ('active', models.BooleanField(default=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='+', to='tenancy.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalogue.category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalogue.level')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('charge_rate', tutortrack.core.fields.RateField(currency_field='currency')),
                ('pay_rate', tutortrack.core.fields.RateField(blank=True, currency_field='currency', null=True)),
                ('pay_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalogue.service')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('exam_boards', models.JSONField(blank=True, default=list)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='catalogue.category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalogue.subject'),
        ),
        migrations.AddField(
            model_name='level',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='catalogue.subject'),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('region', models.CharField(blank=True, default='', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('exempt_reason', models.CharField(blank=True, default='', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.taxrate'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('registration', 'Registration fee'), ('materials', 'Materials'), ('books', 'Books'), ('exam_entry', 'Exam entry'), ('late_cancel', 'Late cancellation fee'), ('travel', 'Travel fee'), ('other', 'Other')], default='other', max_length=15)),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('price', tutortrack.core.fields.MoneyField(currency_field='currency')),
                ('account_code', models.CharField(blank=True, default='', max_length=30)),
                ('tutor_share_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.taxrate')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PackageTemplate',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity_type', models.CharField(choices=[('hours', 'Hours'), ('lessons', 'Lessons'), ('credit', 'Credit')], max_length=8)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('price', tutortrack.core.fields.MoneyField(currency_field='currency')),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('transferable_between_siblings', models.BooleanField(default=False)),
                ('refund_policy', models.CharField(choices=[('none', 'Not refundable'), ('unused_pro_rata', 'Unused part refundable'), ('full', 'Fully refundable before first use')], default='none', max_length=16)),
                ('bookable_online', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('services', models.ManyToManyField(blank=True, related_name='+', to='catalogue.service')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.taxrate')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='category_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='serviceprice',
            constraint=models.UniqueConstraint(fields=('service', 'currency'), name='service_price_currency_unique'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='subject_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('subject', 'name'), name='level_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='taxrate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organisation',), name='one_default_tax_rate'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('pay_rate_amount__isnull', True), ('pay_percent__isnull', True), _connector='OR'), name='service_pay_rate_or_percent'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('charge_rate_amount__gte', 0)), name='service_charge_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='packagetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='package_quantity_gt0'),
        ),
        migrations.AddConstraint(
            model_name='packagetemplate',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__gte', 0)), name='package_price_gte0'),
        ),
            enable_rls("catalogue_category"),
        enable_rls("catalogue_subject"),
        enable_rls("catalogue_level"),
        enable_rls("catalogue_taxrate"),
        enable_rls("catalogue_service"),
        enable_rls("catalogue_serviceprice"),
        enable_rls("catalogue_location"),
        enable_rls("catalogue_room"),
        enable_rls("catalogue_product"),
        enable_rls("catalogue_packagetemplate"),
    ]
