from django.urls import path

from . import views as v

urlpatterns = [
    path("platform/me", v.PlatformMeView.as_view(), name="platform-me"),
    path("platform/tenants", v.TenantListView.as_view(), name="platform-tenants"),
    path("platform/tenants/<uuid:pk>", v.TenantDetailView.as_view(), name="platform-tenant"),
    path("platform/tenants/<uuid:pk>/extend-trial", v.ExtendTrialView.as_view(),
         name="platform-extend-trial"),
    path("platform/tenants/<uuid:pk>/overrides", v.OverridesView.as_view(),
         name="platform-overrides"),
    path("platform/tenants/<uuid:pk>/overrides/<str:key>", v.OverrideView.as_view(),
         name="platform-override"),
    path("platform/tenants/<uuid:pk>/suspend", v.SuspendView.as_view(), name="platform-suspend"),
    path("platform/tenants/<uuid:pk>/unsuspend", v.UnsuspendView.as_view(),
         name="platform-unsuspend"),
    path("platform/tenants/<uuid:pk>/change-plan", v.ChangePlanView.as_view(),
         name="platform-change-plan"),
    path("platform/tenants/<uuid:pk>/resend-verification", v.ResendVerificationView.as_view(),
         name="platform-resend-verification"),
    path("platform/tenants/<uuid:pk>/export", v.ExportView.as_view(), name="platform-export"),
    path("platform/tenants/<uuid:pk>/schedule-deletion", v.ScheduleDeletionView.as_view(),
         name="platform-schedule-deletion"),
    path("platform/tenants/<uuid:pk>/support-sessions", v.SupportSessionView.as_view(),
         name="platform-support-session"),
    path("platform/flags", v.FlagsView.as_view(), name="platform-flags"),
    path("platform/flags/<slug:key>", v.FlagView.as_view(), name="platform-flag"),
    path("platform/flags/<slug:key>/overrides", v.FlagOverridesView.as_view(),
         name="platform-flag-overrides"),
    path("platform/flags/<slug:key>/overrides/<uuid:organisation_id>",
         v.FlagOverrideView.as_view(), name="platform-flag-override"),
    path("platform/operations", v.OperationsView.as_view(), name="platform-operations"),
    path("platform/dead-letters", v.DeadLetterListView.as_view(), name="platform-dead-letters"),
    path("platform/dead-letters/replay", v.ReplayView.as_view(), name="platform-replay"),
    path("platform/notices", v.NoticesView.as_view(), name="platform-notices"),
    path("platform/notices/<uuid:pk>", v.NoticeView.as_view(), name="platform-notice"),
    path("platform/plans", v.PlansView.as_view(), name="platform-plans"),
    path("platform/plans/<slug:key>", v.PlanView.as_view(), name="platform-plan"),
    path("platform/plans/<slug:key>/prices/<int:price_id>", v.PlanPriceView.as_view(),
         name="platform-plan-price"),
]  # fmt: skip
