# Generated by Django 5.2.18 on 2026-10-09 11:03

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models

from tutortrack.core.migrations_utils import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0007_encrypt_tax_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentType',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('data_processing', 'Data processing'), ('photo_video', 'Photos and video'), ('marketing_email', 'Marketing email'), ('marketing_sms', 'Marketing SMS'), ('lesson_recording', 'Lesson recording'), ('terms_of_service', 'Terms of service'), ('privacy_policy', 'Privacy policy'), ('other', 'Other')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('document_url', models.URLField(blank=True, default='')),
                ('required', models.BooleanField(default=False)),
                ('applies_to', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('subject_type', models.CharField(max_length=60)),
                ('subject_id', models.CharField(max_length=64)),
                ('granted', models.BooleanField()),
                ('method', models.CharField(choices=[('form', 'Public form'), ('portal', 'Portal'), ('import', 'Import'), ('staff', 'Recorded by staff'), ('signup', 'Signup')], max_length=10)),
                ('given_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('on_behalf_of_child', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('recorded_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('consent_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='privacy.consenttype')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='consenttype',
            constraint=models.UniqueConstraint(fields=('organisation', 'key'), name='consent_type_key_unique'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['organisation', 'subject_type', 'subject_id', 'consent_type', '-recorded_at'], name='consent_record_subject'),
        ),
        enable_rls("privacy_consenttype"),
        enable_rls("privacy_consentrecord"),
    ]
