# Generated by Django 5.2.18 on 2026-10-10 13:35

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.crypto
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models

from tutortrack.core.migrations_utils import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0007_encrypt_tax_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(choices=[('event', 'When something happens'), ('schedule', 'On a schedule'), ('date', 'Relative to a date'), ('manual', 'Run by hand')], max_length=8)),
                ('trigger_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('subject_type', models.CharField(max_length=40)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=False)),
                ('max_runs_per_record', models.PositiveSmallIntegerField(default=1)),
                ('recipe_key', models.CharField(blank=True, default='', max_length=60)),
                ('webhook_secret', tutortrack.core.crypto.EncryptedField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AutomationVersion',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('trigger_type', models.CharField(max_length=8)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='automations.automation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(max_length=40)),
                ('subject_id', models.CharField(blank=True, default='', max_length=64)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=80)),
                ('run_key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('running', 'Running'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('causation_depth', models.PositiveSmallIntegerField(default=0)),
                ('workflow_id', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('error', models.TextField(blank=True, default='')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automations.automation')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='automations.automationversion')),
            ],
            options={
                'ordering': ['-started_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRunStep',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_key', models.CharField(max_length=60)),
                ('step_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('waiting', 'Waiting')], max_length=10)),
                ('resume_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automations.automationrun')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'constraints': [models.UniqueConstraint(fields=('run', 'step_key'), name='automation_step_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='automationversion',
            constraint=models.UniqueConstraint(fields=('automation', 'version'), name='automation_version_unique'),
        ),
        migrations.AddIndex(
            model_name='automationrun',
            index=models.Index(fields=['automation', 'subject_id', 'started_at'], name='run_record_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationrun',
            constraint=models.UniqueConstraint(fields=('automation', 'subject_id', 'run_key'), name='automation_run_unique'),
        ),
        enable_rls("automations_automation"),
        enable_rls("automations_automationversion"),
        enable_rls("automations_automationrun"),
        enable_rls("automations_automationrunstep"),
    ]
