# Generated by Django 5.2.18 on 2026-10-10 02:14

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.fields
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models

from tutortrack.core.migrations_utils import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0007_encrypt_tax_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ref', models.CharField(max_length=100, unique=True)),
                ('organisation_id', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('legacy', 'Legacy (existing subscribers only)'), ('custom', 'Custom (contact sales)')], default='public', max_length=10)),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='Higher = bigger plan')),
                ('trial_days', models.PositiveSmallIntegerField(default=30)),
                ('seat_mode', models.CharField(choices=[('active', 'Every active tutor'), ('delivered', 'Tutors with a completed lesson in the period')], default='delivered', max_length=10)),
            ],
            options={
                'ordering': ['rank', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_type', models.CharField(choices=[('sms', 'SMS credits'), ('ai', 'AI credits')], max_length=5)),
                ('credits', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('automatic', models.BooleanField(default=False)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('processed_at__isnull', True)), fields=['type'], name='billing_event_unprocessed')],
                'constraints': [models.UniqueConstraint(fields=('event_id',), name='billing_event_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_type', models.CharField(choices=[('sms', 'SMS credits'), ('ai', 'AI credits')], max_length=5)),
                ('allowance', models.PositiveIntegerField(default=0)),
                ('included_balance', models.PositiveIntegerField(default=0)),
                ('purchased_balance', models.IntegerField(default=0)),
                ('used_this_period', models.PositiveIntegerField(default=0)),
                ('period_started_at', models.DateTimeField(blank=True, null=True)),
                ('auto_top_up', models.BooleanField(default=False)),
                ('top_up_pack', models.PositiveIntegerField(default=500)),
                ('low_threshold', models.PositiveIntegerField(default=20)),
                ('allow_overage', models.BooleanField(default=False)),
                ('low_notified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'credit_type'), name='credit_account_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EntitlementOverride',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('int_value', models.PositiveIntegerField(blank=True, null=True)),
                ('unlimited', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation', 'key'), name='entitlement_override_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MeterReport',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.CharField(max_length=40)),
                ('period_date', models.DateField()),
                ('quantity', models.BigIntegerField()),
                ('identifier', models.CharField(max_length=120)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('identifier',), name='meter_report_identifier_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('int_value', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='subscriptions.plan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('plan', 'key'), name='plan_entitlement_unique')],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Annual')], max_length=5)),
                ('component', models.CharField(choices=[('base_fee', 'Base fee'), ('active_tutor', 'Per active tutor'), ('revenue_share', 'Share of payments processed'), ('branch', 'Per extra branch')], max_length=20)),
                ('unit_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('included_quantity', models.PositiveIntegerField(default=0)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='subscriptions.plan')),
            ],
            options={
                'ordering': ['plan', 'currency', 'interval', 'component'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'currency', 'interval', 'component'), name='plan_price_unique')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Annual')], default='month', max_length=5)),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('status', models.CharField(choices=[('trialing', 'Trial'), ('active', 'Active'), ('past_due', 'Payment overdue'), ('suspended', 'Suspended (read-only)'), ('cancelled', 'Cancelled (read-only)')], default='trialing', max_length=10)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=100)),
                ('payment_method', models.JSONField(blank=True, default=dict)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('pending_interval', models.CharField(blank=True, choices=[('month', 'Monthly'), ('year', 'Annual')], max_length=5)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=50)),
                ('cancellation_feedback', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('past_due_since', models.DateTimeField(blank=True, null=True)),
                ('seats', models.PositiveIntegerField(default=0, help_text='Billable tutors last synced')),
                ('seats_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('pending_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='subscriptions.plan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='subscriptions.plan')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organisation',), name='subscription_one_per_org')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UsageCreditLedger',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_type', models.CharField(choices=[('sms', 'SMS credits'), ('ai', 'AI credits')], max_length=5)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('grant', 'Monthly allowance'), ('expiry', 'Unused allowance expired'), ('purchase', 'Top-up'), ('consumption', 'Used'), ('adjustment', 'Adjustment')], max_length=12)),
                ('ref', models.CharField(blank=True, default='', max_length=120)),
                ('balance_after', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'credit_type', 'created_at'], name='subscriptio_organis_965311_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        enable_rls("subscriptions_creditpurchase"),
        enable_rls("subscriptions_billingevent"),
        enable_rls("subscriptions_creditaccount"),
        enable_rls("subscriptions_entitlementoverride"),
        enable_rls("subscriptions_meterreport"),
        enable_rls("subscriptions_subscription"),
        enable_rls("subscriptions_usagecreditledger"),
    ]
