"""Generated report files in object storage (scheduled runs keep their file)."""

from __future__ import annotations

import hashlib
import uuid
from typing import Any

from django.contrib.contenttypes.models import ContentType

from tutortrack.core.context import require_organisation_id
from tutortrack.core.models import StoredFile
from tutortrack.core.permissions import has_perm
from tutortrack.core.storage.client import bucket, s3_client
from tutortrack.core.storage.services import register_access_rule, safe_filename
from tutortrack.core.time import now

from .models import ReportRun


def save(run: ReportRun, filename: str, content_type: str, data: bytes) -> StoredFile:
    """Store server-generated bytes (no upload or malware scan needed) and link to the run."""
    org_id = require_organisation_id()
    key = f"org/{org_id}/{now():%Y/%m}/reports/{uuid.uuid4().hex}/{safe_filename(filename)}"
    s3_client().put_object(Bucket=bucket(), Key=key, Body=data, ContentType=content_type)
    return StoredFile.objects.create(
        filename=filename[:255],
        content_type=content_type,
        size_bytes=len(data),
        checksum_sha256=hashlib.sha256(data).hexdigest(),
        storage_key=key,
        status=StoredFile.Status.UPLOADED,
        scan_status=StoredFile.ScanStatus.CLEAN,
        visibility=StoredFile.Visibility.PRIVATE,
        uploaded_by_id=run.requested_by_id,
        owner_content_type=ContentType.objects.get_for_model(ReportRun),
        owner_object_id=str(run.pk),
    )


def read(stored: StoredFile) -> bytes:
    body: Any = s3_client().get_object(Bucket=bucket(), Key=stored.storage_key)["Body"]
    data: bytes = body.read()
    return data


def _may_open(user: Any, stored: StoredFile) -> bool:
    run = (
        ReportRun.objects.filter(pk=stored.owner_object_id)
        .select_related("scheduled_report__saved_report")
        .first()
    )
    if run is None:
        return False
    if run.requested_by_id == user.pk or has_perm(user, "reporting.manage"):
        return True
    scheduled = run.scheduled_report
    return scheduled is not None and (
        scheduled.saved_report.owner_id == user.pk
        or scheduled.recipients.filter(pk=user.pk).exists()
    )


register_access_rule("reporting.reportrun", _may_open)
