# Generated by Django 5.2.18 on 2026-10-08 15:27

import django.utils.timezone
import tutortrack.core.fields
import tutortrack.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('default_currency', tutortrack.core.fields.CurrencyField(default='GBP', max_length=3)),
                ('timezone', models.CharField(default='Europe/London', max_length=64)),
                ('locale', models.CharField(default='en-GB', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
