# Generated by Django 5.2.18 on 2026-10-08 21:14

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.fields
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enable_rls'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('timezone', models.CharField(max_length=64)),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('locale', models.CharField(max_length=10)),
                ('tax_settings', models.JSONField(blank=True, default=dict)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('email_sender_name', models.CharField(blank=True, default='', max_length=100)),
                ('email_sender_address', models.EmailField(blank=True, default='', max_length=254)),
                ('invoice_prefix', models.CharField(blank=True, default='', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['-is_default', 'name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationDomain',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('type', models.CharField(choices=[('subdomain', 'Subdomain'), ('custom', 'Custom domain')], max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ssl_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('redirect_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='ReservedSlug',
            fields=[
                ('slug', models.SlugField(max_length=63, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organisation',
            name='business_type',
            field=models.CharField(choices=[('sole_trader', 'Sole trader'), ('team', 'Small team'), ('agency', 'Agency'), ('centre', 'Tuition centre'), ('online', 'Online school')], default='sole_trader', max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='company_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='organisation',
            name='country',
            field=models.CharField(default='GB', help_text='ISO 3166-1 alpha-2', max_length=2),
        ),
        migrations.AddField(
            model_name='organisation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='date_format',
            field=models.CharField(choices=[('locale', 'Locale default'), ('dd/MM/yyyy', '31/12/2026'), ('MM/dd/yyyy', '12/31/2026'), ('yyyy-MM-dd', '2026-12-31')], default='locale', max_length=12),
        ),
        migrations.AddField(
            model_name='organisation',
            name='fiscal_year_start_month',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='organisation',
            name='has_demo_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisation',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.storedfile'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='mode',
            field=models.CharField(choices=[('solo', 'Solo'), ('multi', 'Multi-user')], default='solo', max_length=10),
        ),
        migrations.AddField(
            model_name='organisation',
            name='primary_colour',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='organisation',
            name='region',
            field=models.CharField(choices=[('uk', 'United Kingdom'), ('eu', 'European Union'), ('us', 'United States'), ('au', 'Australia')], default='uk', max_length=2),
        ),
        migrations.AddField(
            model_name='organisation',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='suspension_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='organisation',
            name='tax_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='time_format',
            field=models.CharField(choices=[('locale', 'Locale default'), ('24h', '24-hour'), ('12h', '12-hour')], default='locale', max_length=8),
        ),
        migrations.AddField(
            model_name='organisation',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='week_start_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.CheckConstraint(condition=models.Q(('fiscal_year_start_month__gte', 1), ('fiscal_year_start_month__lte', 12)), name='org_fiscal_month_range'),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='organisation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation'),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisationdomain',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenancy.organisation'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organisation', 'code'), name='branch_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organisation',), name='branch_one_default_per_org'),
        ),
    ]
