# Generated by Django 5.2.18 on 2026-10-09 09:13

import tutortrack.core.crypto
from django.db import migrations


def encrypt_existing(apps, schema_editor):
    """Values written before this migration are plaintext; encrypt them in place."""
    from tutortrack.core.crypto import encrypt

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, tax_number FROM tenancy_organisation WHERE tax_number <> ''")
        for pk, value in cursor.fetchall():
            cursor.execute(
                "UPDATE tenancy_organisation SET tax_number = %s WHERE id = %s",
                [encrypt(value), pk],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0006_demo_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='tax_number',
            field=tutortrack.core.crypto.EncryptedField(blank=True, default=''),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
