# Generated by Django 5.2.18 on 2026-10-09 20:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='auto_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancelled_by',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unconfirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonattendee',
            name='charge_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5),
        ),
        migrations.AddField(
            model_name='lessonattendee',
            name='late_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonattendee',
            name='outcome',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('late', 'Late'), ('absent_notified', 'Absent (notified)'), ('no_show', 'No-show'), ('cancelled_client', 'Cancelled by client'), ('cancelled_tutor', 'Cancelled by tutor'), ('cancelled_admin', 'Cancelled by us')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='lessonattendee',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonattendee',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessontutor',
            name='pay_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5),
        ),
    ]
