# Generated by Django 5.2.18 on 2026-10-09 11:10

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models

from tutortrack.core.migrations_utils import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_workflow_links'),
        ('tenancy', '0007_encrypt_tax_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=30)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('target_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('total', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('succeeded', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('shared', models.BooleanField(default=False)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('columns', models.JSONField(blank=True, default=list)),
                ('ordering', models.CharField(blank=True, default='', max_length=60)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('colour', models.CharField(default='#64748b', max_length=7)),
                ('entity_types', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(max_length=60)),
                ('target_id', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.tag')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=6)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, default='', max_length=60)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('recurrence', models.CharField(blank=True, default='', max_length=200)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_at', '-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=60)),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long text'), ('number', 'Number'), ('decimal', 'Decimal'), ('currency', 'Money'), ('date', 'Date'), ('datetime', 'Date and time'), ('boolean', 'Yes/no'), ('select', 'Single choice'), ('multi_select', 'Multiple choice'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('file', 'File'), ('user', 'Staff member'), ('address', 'Address')], max_length=15)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('help_text', models.CharField(blank=True, default='', max_length=300)),
                ('visibility', models.CharField(choices=[('staff', 'Staff'), ('tutor', 'Staff and tutors'), ('client_portal', 'Also in the client portal'), ('public', 'Public forms')], default='staff', max_length=15)),
                ('editable_by', models.CharField(choices=[('staff', 'Staff'), ('tutor', 'Staff and tutors'), ('client', 'Staff, tutors and clients')], default='staff', max_length=10)),
                ('group', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('validation_regex', models.CharField(blank=True, default='', max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['entity_type', 'group', 'order', 'label'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'constraints': [models.UniqueConstraint(fields=('organisation', 'entity_type', 'key'), name='custom_field_key_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(max_length=60)),
                ('target_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('contract', 'Contract'), ('consent_form', 'Consent form'), ('report', 'Report'), ('id', 'Identity document'), ('other', 'Other')], default='other', max_length=15)),
                ('visibility', models.CharField(choices=[('staff_only', 'Staff only'), ('staff_and_tutors', 'Staff and tutors'), ('shared_with_client', 'Shared with the client')], default='staff_only', max_length=20)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.storedfile')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'indexes': [models.Index(fields=['organisation', 'target_type', 'target_id'], name='document_target_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(max_length=60)),
                ('target_id', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('pinned', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('staff_only', 'Staff only'), ('staff_and_tutors', 'Staff and tutors'), ('shared_with_client', 'Shared with the client')], default='staff_only', max_length=20)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('attachments', models.ManyToManyField(blank=True, related_name='+', to='core.storedfile')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'indexes': [models.Index(fields=['organisation', 'target_type', 'target_id'], name='note_target_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='tag_name_unique'),
        ),
        migrations.AddIndex(
            model_name='taggeditem',
            index=models.Index(fields=['organisation', 'target_type', 'target_id'], name='tagged_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='taggeditem',
            constraint=models.UniqueConstraint(fields=('tag', 'target_type', 'target_id'), name='tagged_item_unique'),
        ),
        enable_rls("crm_customfielddefinition"),
        enable_rls("crm_tag"),
        enable_rls("crm_taggeditem"),
        enable_rls("crm_note"),
        enable_rls("crm_task"),
        enable_rls("crm_document"),
        enable_rls("crm_savedview"),
        enable_rls("crm_bulkjob"),
    ]
