"""AWS KMS envelope keys (E29-T02).

Data keys are generated by KMS (``generate_data_key``) and stored only in wrapped form
(the KMS ciphertext, base64) in configuration. At startup each process asks KMS to unwrap
them once and keeps the plaintext in memory; KMS access (IAM) is the real gate.
"""

from __future__ import annotations

import base64
from functools import cache
from typing import Any

from django.conf import settings


def _client() -> Any:
    import boto3

    return boto3.client("kms", region_name=settings.AWS_KMS_REGION or settings.AWS_S3_REGION_NAME)


@cache
def unwrap(wrapped_b64: str) -> bytes:
    """Plaintext of a KMS-wrapped data key (cached per process)."""
    response = _client().decrypt(CiphertextBlob=base64.b64decode(wrapped_b64))
    plaintext: bytes = response["Plaintext"]
    return plaintext


def generate_data_key(key_id: str) -> tuple[bytes, str]:
    """A new 32-byte data key: (plaintext, wrapped base64 to put in configuration)."""
    response = _client().generate_data_key(KeyId=key_id, NumberOfBytes=32)
    return response["Plaintext"], base64.b64encode(response["CiphertextBlob"]).decode()


def clear_cache() -> None:
    unwrap.cache_clear()
