# Generated by Django 5.2.18 on 2026-10-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('people', '0002_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsubject',
            name='catalogue_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.level'),
        ),
        migrations.AddField(
            model_name='tutorsubject',
            name='catalogue_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.subject'),
        ),
    ]
