# Generated by Django 5.2.18 on 2026-10-10 07:25

from django.db import migrations, models


def approved_to_competency(apps, schema_editor):
    TutorSubject = apps.get_model("people", "TutorSubject")
    TutorSubject._default_manager.using(schema_editor.connection.alias).filter(approved=True).update(
        competency="approved"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_tutorsubject_catalogue_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsubject',
            name='competency',
            field=models.CharField(choices=[('claimed', 'Claimed'), ('assessed', 'Assessed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='claimed', max_length=10),
        ),
        migrations.AddField(
            model_name='tutorsubject',
            name='evidence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(approved_to_competency, migrations.RunPython.noop),
    ]
