# Generated by Django 5.2.18 on 2026-10-08 21:14

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipBranch',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='active', max_length=10)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('branch_manager', 'Branch Manager'), ('coordinator', 'Coordinator'), ('finance', 'Finance'), ('tutor', 'Tutor'), ('client', 'Client'), ('student', 'Student'), ('affiliate', 'Affiliate')], max_length=20)),
                ('branch_scope', models.CharField(choices=[('all', 'All'), ('selected', 'Selected')], default='all', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
    ]
