# Generated by Django 5.2.18 on 2026-10-08 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_membershipbranch_user_email_verified_at_membership'),
        ('tenancy', '0002_branch_organisationdomain_reservedslug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.branch'),
        ),
        migrations.AddField(
            model_name='membershipbranch',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipbranch',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.membership'),
        ),
        migrations.AddField(
            model_name='membershipbranch',
            name='organisation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation'),
        ),
        migrations.AddField(
            model_name='membershipbranch',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='+', through='identity.MembershipBranch', to='tenancy.branch'),
        ),
        migrations.AddConstraint(
            model_name='membershipbranch',
            constraint=models.UniqueConstraint(fields=('membership', 'branch'), name='membership_branch_unique'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organisation', 'user'), name='membership_unique'),
        ),
    ]
