# Generated by Django 5.2.18 on 2026-10-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='type',
            field=models.CharField(choices=[('enquiry', 'Enquiry'), ('registration', 'Registration'), ('application', 'Tutor application'), ('custom', 'Other')], default='enquiry', max_length=15),
        ),
    ]
