# Generated by Django 5.2.18 on 2026-10-09 11:58

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.fields
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models

from tutortrack.core.migrations_utils import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('people', '0003_tutorsubject_catalogue_level_and_more'),
        ('tenancy', '0007_encrypt_tax_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('reference', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('seeking_tutor', 'Seeking tutor'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=15)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('charge_rate', tutortrack.core.fields.RateField(blank=True, currency_field='currency', null=True)),
                ('billing_method', models.CharField(choices=[('pay_as_you_go', 'Pay as you go'), ('prepaid_credit', 'Prepaid credit'), ('package', 'Package'), ('recurring_fixed', 'Recurring fixed fee')], default='pay_as_you_go', max_length=16)),
                ('po_number', models.CharField(blank=True, default='', max_length=60)),
                ('default_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('meeting_provider', models.CharField(blank=True, default='', max_length=20)),
                ('default_schedule', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('lessons_per_week', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('expected_total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('goals', models.TextField(blank=True, default='')),
                ('notes_internal', models.TextField(blank=True, default='')),
                ('notes_for_tutor', models.TextField(blank=True, default='')),
                ('notes_for_client', models.TextField(blank=True, default='')),
                ('hours_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('hours_cap_period', models.CharField(choices=[('week', 'Per week'), ('month', 'Per month'), ('total', 'In total')], default='total', max_length=5)),
                ('policy_overrides', models.JSONField(blank=True, default=dict)),
                ('account_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bill_to', models.ForeignKey(blank=True, help_text='Another client pays (e.g. a school or local authority).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='people.client')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='people.client')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.level')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.location')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('package_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.packagetemplate')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.service')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.subject')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=15)),
                ('to_status', models.CharField(max_length=15)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.job')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='JobStudent',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('charge_rate_override', tutortrack.core.fields.RateField(blank=True, currency_field='currency', null=True)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='jobs.job')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_links', to='people.student')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='JobTutor',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('assistant', 'Assistant')], default='lead', max_length=10)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('active', 'Active'), ('ended', 'Ended'), ('declined', 'Declined')], default='active', max_length=10)),
                ('currency', tutortrack.core.fields.CurrencyField(max_length=3)),
                ('pay_rate_override', tutortrack.core.fields.RateField(blank=True, currency_field='currency', null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='jobs.job')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_links', to='people.tutorprofile')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organisation', 'status'], name='job_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('organisation', 'reference'), name='job_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('charge_rate_amount__isnull', True), ('charge_rate_amount__gte', 0), _connector='OR'), name='job_charge_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='jobstudent',
            constraint=models.UniqueConstraint(fields=('job', 'student'), name='job_student_unique'),
        ),
        migrations.AddConstraint(
            model_name='jobtutor',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['offered', 'active'])), fields=('job', 'tutor'), name='job_tutor_current_unique'),
        ),
            enable_rls("jobs_job"),
        enable_rls("jobs_jobstudent"),
        enable_rls("jobs_jobtutor"),
        enable_rls("jobs_jobstatushistory"),
    ]
