# Generated by Django 5.2.18 on 2026-10-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='billing_method',
            field=models.CharField(choices=[('pay_as_you_go', 'Pay as you go'), ('invoice_in_advance', 'Invoice in advance'), ('prepaid_credit', 'Prepaid credit'), ('package', 'Package'), ('recurring_fixed', 'Recurring fixed fee')], default='pay_as_you_go', max_length=18),
        ),
    ]
