# Generated by Django 5.2.18 on 2026-10-10 18:13

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.crypto
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models

from tutortrack.core.migrations_utils import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0007_encrypt_tax_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('user', 'Personal'), ('organisation', 'Organisation')], default='user', max_length=12)),
                ('provider', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('active', 'Connected'), ('error', 'Error'), ('needs_reconnect', 'Needs reconnecting'), ('disconnected', 'Disconnected')], default='active', max_length=16)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('access_token', tutortrack.core.crypto.EncryptedField(blank=True, default='')),
                ('refresh_token', tutortrack.core.crypto.EncryptedField(blank=True, default='')),
                ('secret', tutortrack.core.crypto.EncryptedField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('external_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('error_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', '-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'indexes': [models.Index(fields=['user', 'provider', 'status'], name='integration_user_id_eb72d0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False), models.Q(('status', 'disconnected'), _negated=True)), fields=('organisation', 'user', 'provider'), name='integration_user_provider_unique'), models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('status', 'disconnected'), _negated=True)), fields=('organisation', 'provider'), name='integration_org_provider_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        enable_rls("integrations_integrationconnection"),
    ]
