/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/audit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Audit history for the current organisation (append-only). */
    get: operations["audit_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/audit/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Audit history for the current organisation (append-only). */
    get: operations["audit_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/features": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Feature flags as resolved for the current organisation (drives ``useFeature()``). */
    get: operations["features_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/files/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Direct-to-storage uploads: create -> PUT to ``upload.url`` -> complete -> download. */
    get: operations["files_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/files/{id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Direct-to-storage uploads: create -> PUT to ``upload.url`` -> complete -> download. */
    post: operations["files_complete_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/files/{id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Direct-to-storage uploads: create -> PUT to ``upload.url`` -> complete -> download. */
    get: operations["files_download_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/files/uploads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Direct-to-storage uploads: create -> PUT to ``upload.url`` -> complete -> download. */
    post: operations["files_uploads_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description ``?fields=a,b`` limits output fields on the top-level serializer (``id`` always kept). */
    AuditEntry: {
      /** Format: uuid */
      readonly id: string;
      readonly action: string;
      readonly object_type: string;
      readonly object_id: string;
      readonly object_repr: string;
      readonly changes: unknown;
      /** Format: uuid */
      readonly actor: string | null;
      /** Format: uuid */
      readonly impersonator: string | null;
      readonly ip: string | null;
      readonly request_id: string;
      /** Format: date-time */
      readonly created_at: string;
    };
    Download: {
      /** Format: uri */
      url: string;
      expires_in: number;
    };
    Features: {
      features: {
        [key: string]: boolean;
      };
    };
    FileUploadCreated: {
      file: components["schemas"]["StoredFile"];
      upload: components["schemas"]["PresignedUpload"];
    };
    PaginatedAuditEntryList: {
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
       */
      previous?: string | null;
      results: components["schemas"]["AuditEntry"][];
    };
    PresignedUpload: {
      /** Format: uri */
      url: string;
      method: string;
      headers: {
        [key: string]: string;
      };
      expires_in: number;
    };
    /**
     * @description * `pending` - Pending
     *     * `clean` - Clean
     *     * `infected` - Infected
     *     * `error` - Error
     *     * `skipped` - Skipped
     * @enum {string}
     */
    ScanStatusEnum: "pending" | "clean" | "infected" | "error" | "skipped";
    /**
     * @description * `pending_upload` - Pending Upload
     *     * `uploaded` - Uploaded
     *     * `rejected` - Rejected
     * @enum {string}
     */
    StatusEnum: "pending_upload" | "uploaded" | "rejected";
    /** @description ``?fields=a,b`` limits output fields on the top-level serializer (``id`` always kept). */
    StoredFile: {
      /** Format: uuid */
      readonly id: string;
      readonly filename: string;
      readonly content_type: string;
      readonly size_bytes: number;
      readonly status: components["schemas"]["StatusEnum"];
      readonly scan_status: components["schemas"]["ScanStatusEnum"];
      readonly visibility: components["schemas"]["VisibilityEnum"];
      readonly is_downloadable: boolean;
      /** Format: date-time */
      readonly created_at: string;
    };
    UploadRequestRequest: {
      filename: string;
      content_type: string;
      size_bytes: number;
      /** @default private */
      visibility: components["schemas"]["VisibilityEnum"];
    };
    /**
     * @description * `private` - Private
     *     * `internal` - Internal
     *     * `shared` - Shared
     * @enum {string}
     */
    VisibilityEnum: "private" | "internal" | "shared";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  audit_list: {
    parameters: {
      query?: {
        action?: string;
        actor?: string;
        created_after?: string;
        created_before?: string;
        /** @description The pagination cursor value. */
        cursor?: string;
        /** @description Comma-separated fields to return (sparse). */
        fields?: string;
        object_id?: string;
        object_type?: string;
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description Number of results to return per page. */
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedAuditEntryList"];
        };
      };
    };
  };
  audit_retrieve: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to return (sparse). */
        fields?: string;
      };
      header?: never;
      path: {
        /** @description A UUID string identifying this audit entry. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditEntry"];
        };
      };
    };
  };
  features_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Features"];
        };
      };
    };
  };
  files_retrieve: {
    parameters: {
      query?: {
        /** @description Comma-separated fields to return (sparse). */
        fields?: string;
      };
      header?: never;
      path: {
        /** @description A UUID string identifying this stored file. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StoredFile"];
        };
      };
    };
  };
  files_complete_create: {
    parameters: {
      query?: never;
      header?: {
        /** @description Makes the request safe to retry for 24 hours. */
        "Idempotency-Key"?: string;
      };
      path: {
        /** @description A UUID string identifying this stored file. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StoredFile"];
        };
      };
    };
  };
  files_download_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description A UUID string identifying this stored file. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Download"];
        };
      };
    };
  };
  files_uploads_create: {
    parameters: {
      query?: never;
      header?: {
        /** @description Makes the request safe to retry for 24 hours. */
        "Idempotency-Key"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UploadRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["UploadRequestRequest"];
        "multipart/form-data": components["schemas"]["UploadRequestRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FileUploadCreated"];
        };
      };
    };
  };
}
