# Generated by Django 5.2.18 on 2026-10-10 23:39

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models

from tutortrack.core.migrations_utils import enable_rls


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('integrations', '0001_initial'),
        ('tenancy', '0007_encrypt_tax_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingConnection',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('individual', 'Each invoice, payment and credit note'), ('summary', 'A daily summary journal')], default='individual', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('sync_bills', models.BooleanField(default=True)),
                ('attach_pdf', models.BooleanField(default=True)),
                ('lock_behaviour', models.CharField(choices=[('post_to_open', 'Post on the first open date, with a note'), ('hold', 'Hold it until the period is unlocked')], default='post_to_open', max_length=12)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('base_currency', models.CharField(blank=True, default='', max_length=3)),
                ('lock_date', models.DateField(blank=True, null=True)),
                ('chart', models.JSONField(blank=True, default=dict)),
                ('chart_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('schedule_id', models.CharField(blank=True, default='', max_length=255)),
                ('backfill', models.JSONField(blank=True, default=dict)),
                ('last_digest_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='integrations.integrationconnection')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalRecordLink',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('object_type', models.CharField(max_length=20)),
                ('object_id', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('external_id', models.CharField(blank=True, default='', max_length=100)),
                ('external_number', models.CharField(blank=True, default='', max_length=100)),
                ('synced_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Waiting to sync'), ('synced', 'Synced'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=8)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('workflow_id', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='accounting.accountingconnection')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SyncLogEntry',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('unchanged', 'Already up to date'), ('voided', 'Voided'), ('error', 'Error'), ('retrying', 'Will retry'), ('skipped', 'Skipped')], max_length=10)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='accounting.externalrecordlink')),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'sync log entries',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TaxMapping',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalogue.taxrate')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TrackingMapping',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('category_id', models.CharField(max_length=100)),
                ('option_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.branch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=20)),
                ('key', models.CharField(default='default', max_length=80)),
                ('external_id', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'kind', 'key'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'constraints': [models.UniqueConstraint(fields=('organisation', 'provider', 'kind', 'key'), name='account_mapping_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='externalrecordlink',
            index=models.Index(fields=['organisation', 'status'], name='acct_link_status_idx'),
        ),
        migrations.AddIndex(
            model_name='externalrecordlink',
            index=models.Index(fields=['object_type', 'object_id'], name='acct_link_object_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalrecordlink',
            constraint=models.UniqueConstraint(fields=('connection', 'object_type', 'object_id'), name='external_record_unique'),
        ),
        migrations.AddConstraint(
            model_name='taxmapping',
            constraint=models.UniqueConstraint(fields=('organisation', 'provider', 'tax_rate'), name='tax_mapping_unique'),
        ),
        migrations.AddConstraint(
            model_name='taxmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_rate__isnull', True)), fields=('organisation', 'provider'), name='tax_mapping_no_tax_unique'),
        ),
        migrations.AddConstraint(
            model_name='trackingmapping',
            constraint=models.UniqueConstraint(fields=('organisation', 'provider', 'branch'), name='tracking_mapping_unique'),
        ),
        enable_rls("accounting_accountingconnection"),
        enable_rls("accounting_accountmapping"),
        enable_rls("accounting_taxmapping"),
        enable_rls("accounting_trackingmapping"),
        enable_rls("accounting_externalrecordlink"),
        enable_rls("accounting_synclogentry"),
    ]
