# Generated by Django 5.2.18 on 2026-10-09 06:35

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models

from tutortrack.core.migrations_utils import enable_rls


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enable_rls'),
        ('tenancy', '0006_demo_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleLink',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_id', models.CharField(max_length=255)),
                ('process', models.CharField(max_length=60)),
                ('paused', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'constraints': [models.UniqueConstraint(fields=('organisation', 'schedule_id'), name='schedule_link_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowLink',
            fields=[
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow_id', models.CharField(max_length=255)),
                ('run_id', models.CharField(blank=True, default='', max_length=64)),
                ('workflow_type', models.CharField(max_length=100)),
                ('process', models.CharField(db_index=True, max_length=60)),
                ('task_queue', models.CharField(default='default', max_length=40)),
                ('subject_type', models.CharField(blank=True, default='', max_length=60)),
                ('subject_id', models.CharField(blank=True, default='', max_length=64)),
                ('branch_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated'), ('timed_out', 'Timed Out')], default='running', max_length=12)),
                ('current_step', models.CharField(blank=True, default='', max_length=60)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenancy.organisation')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'abstract': False,
                'base_manager_name': 'all_tenants',
                'indexes': [models.Index(fields=['organisation', 'subject_type', 'subject_id'], name='workflow_link_subject')],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'workflow_id'), name='workflow_link_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_tenants', django.db.models.manager.Manager()),
            ],
        ),
        enable_rls("core_workflowlink"),
        enable_rls("core_schedulelink"),
    ]
