# Generated by Django 5.2.18 on 2026-10-10 02:46

import django.db.models.deletion
import django.utils.timezone
import tutortrack.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workflow_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='rollout_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlatformNotice',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=tutortrack.core.ids.new_id, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Degraded service'), ('outage', 'Outage')], default='info', max_length=10)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
    ]
